from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(309, 343)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonOK = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOK.setGeometry(QtCore.QRect(170, 0, 51, 21))
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.IPLine = QtWidgets.QLineEdit(self.centralwidget)
        self.IPLine.setGeometry(QtCore.QRect(30, 0, 133, 20))
        self.IPLine.setText("")
        self.IPLine.setObjectName("IPLine")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 21, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 211, 21))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButtonSSH = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSSH.setGeometry(QtCore.QRect(20, 100, 75, 23))
        self.pushButtonSSH.setObjectName("pushButtonSSH")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButtonTelnet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonTelnet.setGeometry(QtCore.QRect(20, 140, 75, 23))
        self.pushButtonTelnet.setObjectName("pushButtonTelnet")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 103, 131, 20))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 143, 200, 20))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 210, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.WebLine = QtWidgets.QLineEdit(self.centralwidget)
        self.WebLine.setGeometry(QtCore.QRect(10, 260, 221, 20))
        self.WebLine.setText("")
        self.WebLine.setObjectName("WebLine")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 240, 270, 16))
        self.label_7.setObjectName("label_7")
        self.pushButtonHTTP = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonHTTP.setGeometry(QtCore.QRect(10, 280, 75, 23))
        self.pushButtonHTTP.setObjectName("pushButtonHTTP")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(100, 280, 161, 20))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.pushButtonFTP = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonFTP.setGeometry(QtCore.QRect(20, 180, 75, 23))
        self.pushButtonFTP.setObjectName("pushButtonFTP")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(110, 180, 151, 21))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 309, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TestYourSM"))
        self.pushButtonOK.setText(_translate("MainWindow", "OK"))
        self.label.setText(_translate("MainWindow", "IP:"))
        self.pushButtonSSH.setText(_translate("MainWindow", "SSH test"))
        self.label_3.setText(_translate("MainWindow", "Available ip tests:"))
        self.pushButtonTelnet.setText(_translate("MainWindow", "Telnet test"))
        self.label_6.setText(_translate("MainWindow", "Website test:"))
        self.label_7.setText(_translate("MainWindow", "Please enter the website address to check: "))
        self.pushButtonHTTP.setText(_translate("MainWindow", "Start"))
        self.pushButtonFTP.setText(_translate("MainWindow", "FTP test"))
